#!/usr/bin/env bash
# medkit — offline-first setup helper.
#
# Idempotent. Run once before `docker compose -f docker-compose.offline.yml up`.
#
# What it does:
#   1. Verifies docker + docker compose are installed.
#   2. Generates livekit/livekit.yaml from the template with a fresh API
#      secret if one doesn't exist yet.
#   3. Writes backend/.env.local with sensible offline defaults if missing.
#   4. Pulls the default Ollama model (medgemma1.5:4b) — relies on the
#      compose stack being up; uses `docker exec` so we don't need
#      Ollama installed on the host.
#   5. Pre-pulls Piper voices and faster-whisper model into the named
#      volumes so the first compose-up doesn't block on downloads.
#
# Usage:
#   ./scripts/setup-offline.sh           # full setup
#   ./scripts/setup-offline.sh --no-pull # skip model pulls (config only)

set -euo pipefail

SCRIPT_DIR="$(cd -- "$(dirname -- "${BASH_SOURCE[0]}")" &>/dev/null && pwd)"
ROOT_DIR="$(cd -- "$SCRIPT_DIR/.." &>/dev/null && pwd)"

NO_PULL=0
for arg in "$@"; do
  case "$arg" in
    --no-pull) NO_PULL=1 ;;
    *) echo "unknown arg: $arg" >&2; exit 2 ;;
  esac
done

green() { printf "\033[32m%s\033[0m\n" "$1"; }
yellow() { printf "\033[33m%s\033[0m\n" "$1"; }
red() { printf "\033[31m%s\033[0m\n" "$1"; }

green "[1/5] Checking prerequisites"
if ! command -v docker >/dev/null 2>&1; then
  red "docker is not installed. Install Docker Desktop or Docker Engine first."
  exit 1
fi
if ! docker compose version >/dev/null 2>&1; then
  red "docker compose plugin is missing. Install docker-compose-plugin."
  exit 1
fi

green "[2/5] Generating LiveKit config"
LIVEKIT_DIR="$ROOT_DIR/livekit"
LIVEKIT_CONFIG="$LIVEKIT_DIR/livekit.yaml"
LIVEKIT_TEMPLATE="$LIVEKIT_DIR/livekit.yaml.template"
mkdir -p "$LIVEKIT_DIR"

if [[ -f "$LIVEKIT_CONFIG" ]]; then
  yellow "  livekit.yaml already exists — leaving it untouched"
  LIVEKIT_API_SECRET="$(grep -E '^[[:space:]]+devkey:' "$LIVEKIT_CONFIG" | awk '{print $2}' | tr -d '"' | head -1)"
else
  if [[ ! -f "$LIVEKIT_TEMPLATE" ]]; then
    red "missing $LIVEKIT_TEMPLATE — checkout incomplete?"
    exit 1
  fi
  LIVEKIT_API_SECRET="$(openssl rand -hex 32 2>/dev/null || head -c 32 /dev/urandom | base64 | tr -dc 'a-zA-Z0-9' | head -c 64)"
  sed "s|__LIVEKIT_API_SECRET__|$LIVEKIT_API_SECRET|" "$LIVEKIT_TEMPLATE" >"$LIVEKIT_CONFIG"
  green "  wrote $LIVEKIT_CONFIG"
fi

green "[3/5] Writing backend/.env.local defaults (if absent)"
ENV_FILE="$ROOT_DIR/backend/.env.local"
if [[ -f "$ENV_FILE" ]]; then
  yellow "  $ENV_FILE already exists — leaving it untouched"
else
  cat >"$ENV_FILE" <<EOF
# Generated by scripts/setup-offline.sh — safe to edit.
LLM_PROVIDER=ollama
STT_PROVIDER=whisper
TTS_PROVIDER=piper
LIVEKIT_MODE=local

OLLAMA_BASE_URL=http://ollama:11434
OLLAMA_MODEL_PATIENT=medgemma1.5:4b
OLLAMA_MODEL_ATTENDING=medgemma1.5:4b

WHISPER_URL=http://whisper:5001
WHISPER_MODEL=small.en

PIPER_URL=http://piper:5002

LIVEKIT_URL=ws://livekit:7880
LIVEKIT_API_KEY=devkey
LIVEKIT_API_SECRET=$LIVEKIT_API_SECRET

# Optional fallbacks — set if you want them in the chain.
# LLM_FALLBACK_CHAIN=ollama,gemini,claude
# GEMINI_API_KEY=
# ANTHROPIC_API_KEY=
EOF
  green "  wrote $ENV_FILE"
fi

if [[ "$NO_PULL" -eq 1 ]]; then
  green "Skipping model pulls (--no-pull). Run \`docker compose -f docker-compose.offline.yml up\` to start."
  exit 0
fi

green "[4/5] Pulling default Ollama model (medgemma1.5:4b)"
pushd "$ROOT_DIR" >/dev/null
docker compose -f docker-compose.offline.yml up -d ollama
# Wait for the container to become healthy or at least responsive.
for i in {1..30}; do
  if docker exec medkit-ollama ollama list >/dev/null 2>&1; then
    break
  fi
  if [[ "$i" -eq 30 ]]; then
    red "  ollama did not become responsive after 30 retries"
    exit 1
  fi
  sleep 2
done
if docker exec medkit-ollama ollama list 2>/dev/null | grep -q "medgemma1.5:4b"; then
  yellow "  medgemma1.5:4b already pulled — skipping"
else
  docker exec medkit-ollama ollama pull medgemma1.5:4b
fi
popd >/dev/null

green "[5/5] Pre-pulling Piper voices and faster-whisper model"
"$SCRIPT_DIR/pull-piper-voices.sh"
"$SCRIPT_DIR/pull-whisper-model.sh"

green ""
green "Done. Start the full stack with:"
green "  docker compose -f docker-compose.offline.yml up"
